using System.Collections.Specialized;
using System.Text.Json.Serialization;
using Xray.Config.Enums;

namespace Xray.Config.Models;

/// <summary>
/// Renamed from the TCP transport layer (the original name was ambiguous), the outgoing RAW transport layer sends TCP and UDP data generated by proxy protocol wrappers directly, and the kernel does not use other transport layers (such as XHTTP) to transmit its traffic.
/// </summary>
public class RawSettings
{
    /// <summary>
    /// For incoming connections only, specifies whether to accept the PROXY protocol.
    /// </summary>
    [JsonPropertyName("acceptProxyProtocol")]
    public bool AcceptProxyProtocol { get; set; }

    /// <summary>
    /// Data packet header masking settings, default value: NoneHeaderObject.
    /// </summary>
    [JsonPropertyName("header")]
    public BaseSettingsHeaders? Header { get; set; }
}

public abstract class BaseSettingsHeaders
{
    [JsonPropertyName("type")]
    public HeadersType Type { get; set; }

    public BaseSettingsHeaders(HeadersType type)
    {
        Type = type;
    }
}

/// <summary>
/// No masking is performed.
/// </summary>
public class NoneSettingsHeaders : BaseSettingsHeaders
{
    public NoneSettingsHeaders() : base(HeadersType.None) { }
}

/// <summary>
/// The HTTP cloaking configuration must be the same on both the incoming and outgoing connection, and its contents must match.
/// </summary>
public class HttpSettingsHeaders : BaseSettingsHeaders
{
    public HttpSettingsHeaders() : base(HeadersType.Http) { }

    /// <summary>
    /// HTTP request.
    /// </summary>
    [JsonPropertyName("request")]
    public HttpRequest Request { get; set; } = new();

    /// <summary>
    /// HTTP response.
    /// </summary>
    [JsonPropertyName("response")]
    public HttpRequest Response { get; set; } = new();
}

/// <summary>
/// Raw HTTP request model.
/// </summary>
public class HttpRequest
{
    /// <summary>
    /// HTTP version, default value is "1.1".
    /// </summary>
    [JsonPropertyName("version")]
    public string? Version { get; set; }

    /// <summary>
    /// HTTP method, default value is "GET".
    /// </summary>
    [JsonPropertyName("method")]
    public string? Method { get; set; }

    /// <summary>
    /// Path, array of strings. The default value is ["/"]. If there are multiple values, one is randomly selected for each request.
    /// </summary>
    [JsonPropertyName("path")]
    public List<string> Path { get; set; } = new();

    /// <summary>
    /// HTTP headers, key-value pairs, where each key represents the name of an HTTP header and the corresponding value is an array.
    /// </summary>
    [JsonPropertyName("headers")]
    public NameValueCollection Headers { get; set; } = new();
}

/// <summary>
/// Raw HTTP response model.
/// </summary>
public class HttpResponse
{
    /// <summary>
    /// HTTP version, default value is "1.1".
    /// </summary>
    [JsonPropertyName("version")]
    public string? Version { get; set; }

    /// <summary>
    /// HTTP status, default value is "200".
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// HTTP status description, default value is "OK".
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    /// <summary>
    /// HTTP headers, key-value pairs, where each key represents the name of an HTTP header and the corresponding value is an array.
    /// </summary>
    [JsonPropertyName("headers")]
    public NameValueCollection Headers { get; set; } = new();
}
