using System.Text.Json.Serialization;
using Xray.Config.Enums;

namespace Xray.Config.Models;

/// <summary>
/// Reality Configuration. Reality is Xray's original technology. Reality provides a higher level of security than TLS and is configured in the same way as TLS.
/// </summary>
public class RealitySettings
{
    /// <summary>
    /// If the value is true, print debugging information.
    /// </summary>
    [JsonPropertyName("show")]
    public bool Show { get; set; } = true;

    // TODO: alias as dest?
    /// <summary>
    /// Required parameter, format is the same as dest in VLESS fallbacks.
    /// </summary>
    [JsonPropertyName("target")]
    public dynamic? Target { get; set; }

    /// <summary>
    /// An optional parameter, the format is the same as <see href="https://xtls.github.io/config/features/fallback.html#fallbackobject">xver</see> in VLESS fallbacks.
    /// </summary>
    [JsonPropertyName("xver")]
    public int? XVer { get; set; }

    /// <summary>
    /// Required parameter, list of those available serverName to the client, wildcards * are not supported yet.
    /// </summary>
    [JsonPropertyName("serverNames")]
    public List<string> ServerNames { get; set; } = new List<string>() { string.Empty };

    /// <summary>
    /// A required parameter, generated using the command ./xray x25519.
    /// </summary>
    [JsonPropertyName("privateKey")]
    public string? PrivateKey { get; set; }

    /// <summary>
    /// Optional parameter, minimum version of Xray client, format: x.y.z.
    /// </summary>
    [JsonPropertyName("minClientVer")]
    public string? MinClientVer { get; set; }

    /// <summary>
    /// Optional parameter, maximum version of Xray client, format: x.y.z.
    /// </summary>
    [JsonPropertyName("maxClientVer")]
    public string? MaxClientVer { get; set; }

    /// <summary>
    /// An optional parameter, the maximum allowed time difference in milliseconds.
    /// </summary>
    [JsonPropertyName("maxTimeDiff")]
    public int? MaxTimeDiff { get; set; }

    /// <summary>
    /// A mandatory parameter, the list of available shortId for the client, can be used to distinguish between different clients.
    /// <para>For format requirements, see shortId.</para>
    /// <para>If it contains an empty value, shortId the client may be empty.</para>
    /// </summary>
    [JsonPropertyName("shortIds")]
    public List<string>? ShortIds { get; set; }

    /// <summary>
    /// For server use only. A private key used to add an additional post-quantum signature using the ML-DSA-65 scheme to the certificate issued to the Reality client.
    /// </summary>
    [JsonPropertyName("mldsa65Seed")]
    public string? Mldsa65Seed { get; set; }

    // TODO: add limitFallbackUpload/limitFallbackDownload

    /// <summary>
    /// Optional parameter. Speed ​​limit for backup REALITY connections. The limit takes effect after the specified number of bytes have been transferred. Defaults to 0.
    /// </summary>
    [JsonPropertyName("afterBytes")]
    public int? AfterBytes { get; set; }

    /// <summary>
    /// Optional parameter. Rate limit for REALITY backup connections. Specifies the base rate (bytes/second). The default is 0, which disables rate limiting.
    /// </summary>
    [JsonPropertyName("bytesPerSec")]
    public int? BytesPerSec { get; set; }

    /// <summary>
    /// Optional parameter. Rate limit for backup REALITY connections. Specifies the burst rate (bytes/second). Effective when the value is greater than bytesPerSec.
    /// </summary>
    [JsonPropertyName("burstBytesPerSec")]
    public int? BurstBytesPerSec { get; set; }

    /// <summary>
    /// One of serverNames the servers.
    /// <para>If serverNames the server contains an empty value, then, as with TLS, the client can use it "serverName": "0.0.0.0" to establish a connection without SNI. Unlike TLS, REALITY does not require or have an option to allow insecure connections for this feature. When using this feature, ensure that dest you return the default certificate when accepting connections without SNI.</para>
    /// </summary>
    [JsonPropertyName("serverName")]
    public string? ServerName { get; set; }

    /// <summary>
    /// A required parameter, the same as in TLSObject .
    /// </summary>
    [JsonPropertyName("fingerprint")]
    public Fingerprint Fingerprint { get; set; } = Fingerprint.Chrome;

    // TODO: add alias publicKey
    /// <summary>
    /// Required parameter: public key corresponding to the server's private key. Generated by the command
    /// <code>./xray x25519 -i "server secret key".</code>
    /// </summary>
    [JsonPropertyName("password")]
    public string? Password { get; set; }

    /// <summary>
    /// Optional parameter. The public key for verifying the ML-DSA-65 signature. If this field is not empty, the client will use the specified key to validate the certificate returned by the server. For details, see the parameter description "mldsa65Seed".
    /// </summary>
    [JsonPropertyName("mldsa65Verify")]
    public string? Mldsa65Verify { get; set; }

    /// <summary>
    /// One of shortIds the servers.
    /// <para>Length is 8 bytes, that is 16 hexadecimal digits (0-f), it can be less than 16, the kernel will automatically add 0 to the end, but the number of digits must be even (because one byte consists of 2 hexadecimal digits).</para>
    /// <para>0 is also an even number, so if shordIds the server contains an empty value "", the client may also be empty.</para>
    /// </summary>
    [JsonPropertyName("shortId")]
    public string? ShortId { get; set; }

    /// <summary>
    /// The initial path and parameters for the crawler, it is recommended to use different ones for each client.
    /// </summary>
    [JsonPropertyName("spiderX")]
    public string? SpiderX { get; set; }
}
